version: "3.7"
services:
  php:
    image: php:7.4.0-fpm
    container_name: "paa-php"
    volumes:
      - ./:/app/paa_thinkphp6
    environment:
      - APP_DEBUG=true
      - TZ=Asia/Shanghai
    command: php-fpm

  nginx:
    image: "nginx:1.17"
    container_name: "paa-web"
    ports:
      - "8000:80"
    links:
      - php
    volumes:
      - ./:/app/paa_thinkphp6
      - ./runtime/nginx:/etc/nginx/conf.d
      - ./runtime/nginx/log:/var/log/nginx
    depends_on:
      - "php"
